"""Schemas module exports."""
from app.schemas.schemas import (
    UserBase,
    UserCreate,
    UserResponse,
    TokenResponse,
    OAuthCallbackRequest,
    EmailSummary,
    EmailAnalysisResult,
    ScanRequest,
    ScanResponse,
    DashboardStats,
    TelegramConnectRequest,
    TelegramConnectResponse,
    NotificationPreferences,
    UserSettings,
    UpdateSettingsRequest,
    AdminStats,
    DetectionRuleCreate,
    DetectionRuleResponse,
    PhishingExample,
    SecurityTip,
)

__all__ = [
    "UserBase",
    "UserCreate", 
    "UserResponse",
    "TokenResponse",
    "OAuthCallbackRequest",
    "EmailSummary",
    "EmailAnalysisResult",
    "ScanRequest",
    "ScanResponse",
    "DashboardStats",
    "TelegramConnectRequest",
    "TelegramConnectResponse",
    "NotificationPreferences",
    "UserSettings",
    "UpdateSettingsRequest",
    "AdminStats",
    "DetectionRuleCreate",
    "DetectionRuleResponse",
    "PhishingExample",
    "SecurityTip",
]
